### ISSUE TITLE
Save keyboard layout, location & notification

### ISSUE THREAD

**Issue by adrienluitot** [mayankmetha/Rucky#22]
Hello !

I've tested Rucky and it seems to work well. :D

I see few improvements though, like the possibility to change the default keyboard layout maybe in the settings or to keep the last one use instead of getting back to the American one.

Also, I don't understand why there must be always the notification and why it's seems to always be launched.
Is it possible to remove this ?

Last thing, I didn't understand why we need the location permission ?

Thanks in advance !

**Comment by mayankmetha** [comment]
> Hello !
> 
> 
> 
> I've tested Rucky and it seems to work well. :D
> 
> 
> 
> I see few improvements though, like the possibility to change the default keyboard layout maybe in the settings or to keep the last one use instead of getting back to the American one.
> 
> 
> 
> Also, I don't understand why there must be always the notification and why it's seems to always be launched.
> 
> Is it possible to remove this ?
> 
> 
> 
> Last thing, I didn't understand why we need the location permission ?
> 
> 
> 
> Thanks in advance !

Thanks for the feature improvement - Persist keyboard layout option will be added to ToDo list for next update.

Always on notification is kept as the onPlug USB option doesn't work on some devices with aggressive power saving background task killers like those found on Nokia and OnePlus Stock ROMs. A persistent notification will not kill the app. A featured borrowed from the music players. 

Location permission was added for the raspberry pi feature. Certain network api's like mDNS is weirdly given location permission category in Android. To be frank Android Permission documentations do not match with the AOSP codebase, due to this certain required permissions are actually not required. I too noticed this while implementing the feature. If you aren't using Raspberry Pi feature, you can kindly disable the permission. 

Regards,
Mayank

**Comment by adrienluitot** [comment]
Nice for the persistence !

Isn't there a possibility to disable this, like if the onPlug USB option is disable ?

I tried to disable the permission, but when I do the application crash and don't start.

**Comment by mayankmetha** [comment]
> Nice for the persistence !
> 
> 
> 
> Isn't there a possibility to disable this, like if the onPlug USB option is disable ?
> 
> 
> 
> I tried to disable the permission, but when I do the application crash and don't start.

Will look into this notification issue option too, to allow user to enable/disable notification based on settings of on-demand features.

**Comment by adrienluitot** [comment]
Thanks, that's very kind! :D

And about the crash due to permission' ?

**Comment by mayankmetha** [comment]
> Thanks, that's very kind! :D
> 
> 
> 
> And about the crash due to permission' ?

Crash is due to the network protocol APIs used in the app for communicating with raspberry pi and update service (non NetHunter version) which depend on the location permission. I'm trying a work around to get the APIs to work without the permission requirements.

**Comment by adrienluitot** [comment]
You are awesome ! Thanks !
